### ISSUE TITLE
lein uberjar error

### ISSUE THREAD

**Issue by ghostandthemachine** [overtone/overtone#140]
I am trying to make an OSX .app version of mini beast. To do this I need to make an uberjar of the project. When trying to do that I ran in to an error. After looking into it I thought it came from Overtone. I then tried creating an uberjar of Overtone and had the same error. Not sure if this is a known issue or if Overtone is just not meant to be packaged in an uberjar. 

It's a duplicate entry error thrown by a java.util.zip.ZipException. Here is the error:

jonrose@Jon-Roses-MacBook-Pro ~/c/p/overtone> lein uberjar
Could not find artifact org.clojure:clojure:pom:1.+ in central (http://repo1.maven.org/maven2)
Could not find artifact org.clojure:clojure:pom:1.+ in clojars (https://clojars.org/repo/)
Could not find artifact org.clojure:clojure:pom:1.+ in stuartsierra-releases (http://stuartsierra.com/maven2)
Created /Users/jonrose/code/projects/overtone/target/overtone-0.8.0-SNAPSHOT.jar
Could not find artifact org.clojure:clojure:pom:1.+ in central (http://repo1.maven.org/maven2)
Could not find artifact org.clojure:clojure:pom:1.+ in clojars (https://clojars.org/repo/)
Could not find artifact org.clojure:clojure:pom:1.+ in stuartsierra-releases (http://stuartsierra.com/maven2)
Including overtone-0.8.0-SNAPSHOT.jar
Including swingx-painters-1.6.3.jar
Including byte-spec-0.3.1.jar
Including data.json-0.1.2.jar
Including at-at-1.0.0.jar
Including swingx-action-1.6.3.jar
Including clj-native-0.9.2-SNAPSHOT.jar
Including miglayout-3.7.4.jar
Including jna-3.4.0.jar
Including core.incubator-0.1.0.jar
Including swingx-autocomplete-1.6.3.jar
Including seesaw-1.4.1.jar
Including forms-1.2.1.jar
Including clj-glob-1.0.0.jar
Including midi-clj-0.4.0.jar
Including j18n-1.0.0.jar
Including clojure-1.3.0.jar
Including swingx-core-1.6.3.jar
Including swingx-plaf-1.6.3.jar
Including core.logic-0.6.5.jar
Including commons-net-3.0.1.jar
Including scsynth-3.5.3-SNAPSHOT.jar
Including jmdns-3.2.1.jar
java.util.zip.ZipException: duplicate entry: com/strangeberry/jmdns/tools/Browser$1.class
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:175)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at leiningen.uberjar$copy_entries$iter__2000__2004$fn__2005.invoke(uberjar.clj:36)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.next(RT.java:587)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.core.protocols$fn__5883.invoke(protocols.clj:128)
    at clojure.core.protocols$fn__5854$G__5849__5863.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__5875.invoke(protocols.clj:54)
    at clojure.core.protocols$fn__5828$G__5823__5841.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6030)
    at clojure.core$into.invoke(core.clj:6077)
    at leiningen.uberjar$include_dep.invoke(uberjar.clj:47)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:605)
    at clojure.core$partial$fn__4072.doInvoke(core.clj:2345)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.core.protocols$fn__5883.invoke(protocols.clj:128)
    at clojure.core.protocols$fn__5854$G__5849__5863.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
    at clojure.core.protocols$fn__5877.invoke(protocols.clj:48)
    at clojure.core.protocols$fn__5828$G__5823__5841.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6030)
    at leiningen.uberjar$write_components.invoke(uberjar.clj:54)
    at leiningen.uberjar$uberjar$fn__2027.invoke(uberjar.clj:95)
    at leiningen.uberjar$uberjar.invoke(uberjar.clj:88)
    at leiningen.uberjar$uberjar.invoke(uberjar.clj:98)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__823.doInvoke(main.clj:73)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:95)
    at leiningen.core.main$_main$fn__862.invoke(main.clj:156)
    at leiningen.core.main$_main.doInvoke(main.clj:155)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

**Comment by seewalker** [comment]
Hi, is there progress on this issue? When following rogerallen's suggestions, I ran into a "Error: Could not find or load main class" error, and when following kevinstadler's suggestion of manually adding the main class to the jar I ran into the same problem.

My approach of manually adding the class (and maybe this is my problem) was `$ jar uf cochlea-0.1.0-SNAPSHOT-standalone.jar ../base+system+user+dev/classes/cochlea/core.class`.  I'm working with overtone 0.9.1 and leiningen 2.5.1.

**Comment by kevinstadler** [comment]
@seewalker yeah your command adds the class file in the wrong directory within the jar, try something like the following (see also the shell script I linked to above):

    jar uf cochlea-0.1.0-SNAPSHOT-standalone.jar -C ../base+system+user+dev/classes cochlea

**Comment by BorisKourt** [comment]
Hi @kevinstadler I've been trying your solution. 

What would cause the script to hang on `Compiling myns.core`. 

Should there be a `(:gen-class)` line in the main ns? 

Thanks!

**Comment by BorisKourt** [comment]
Looks like the `lein compile` step fails with the following: 

```
java.lang.NoClassDefFoundError: overtone/sc/machinery/server/native/callback_be1e9461_b2df_484f_83da_42801206a7bf, compiling:(overtone/sc/machinery/server/native.clj:25:1)
Exception in thread "main" java.lang.NoClassDefFoundError: overtone/sc/machinery/server/native/callback_be1e9461_b2df_484f_83da_42801206a7bf, compiling:(overtone/sc/machinery/server/native.clj:25:1)
```

**Comment by kevinstadler** [comment]
As I wrote above the `lein compile` step is expected to fail, but at least in my case it still produced the necessary class files and left them in target/classes, from where they can be added to the jar (see the bash script that I linked to above). The ns with the main method should definitely contain a `(:gen-class)`, yes.

**Comment by BorisKourt** [comment]
Thanks for your reply!

I was able to get it to package it, had to adjust `$PROJECT` as my root directory didn't match the project name. 

I get the issues below when I start to run it. (**Excuse the massive stack trace!**) 

Just wondering if you ran into this and this is just a configuration issue on my part?

```sh
java.lang.UnsatisfiedLinkError: Unable to load library 'scsynth': dlopen(libscsynth.dylib, 9): image not found
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:368)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at overtone.sc.machinery.server.native$eval10551$fn__10552$fn__10560.invoke(native.clj:35)
        at clj_native.direct$loadlib.invokeStatic(direct.clj:147)
        at clj_native.direct$loadlib.invoke(direct.clj:143)
        at overtone.sc.machinery.server.native$eval10551$fn__10552.invoke(native.clj:169)
        at overtone.sc.machinery.server.native$eval10551.invokeStatic(native.clj:26)
        at overtone.sc.machinery.server.native$eval10551.invoke(native.clj:25)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5778)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:650)
        at clojure.core$use.invokeStatic(core.clj:5860)
        at clojure.core$use.doInvoke(core.clj:5860)
        at clojure.lang.RestFn.invoke(RestFn.java:930)
        at overtone.sc.machinery.server.connection$eval9724$loading__5569__auto____9725.invoke(connection.clj:1)
        at overtone.sc.machinery.server.connection$eval9724.invokeStatic(connection.clj:1)
        at overtone.sc.machinery.server.connection$eval9724.invoke(connection.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5778)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:650)
        at clojure.core$use.invokeStatic(core.clj:5860)
        at clojure.core$use.doInvoke(core.clj:5860)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at overtone.sc.server$eval9310$loading__5569__auto____9311.invoke(server.clj:1)
        at overtone.sc.server$eval9310.invokeStatic(server.clj:1)
        at overtone.sc.server$eval9310.invoke(server.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5778)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:650)
        at clojure.core$use.invokeStatic(core.clj:5860)
        at clojure.core$use.doInvoke(core.clj:5860)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at overtone.sc.buffer$eval8966$loading__5569__auto____8967.invoke(buffer.clj:1)
        at overtone.sc.buffer$eval8966.invokeStatic(buffer.clj:1)
        at overtone.sc.buffer$eval8966.invoke(buffer.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:3894)
        at sound.tone$eval9$loading__5569__auto____10.invoke(tone.clj:4)
        at sound.tone$eval9.invokeStatic(tone.clj:4)
        at sound.tone$eval9.invoke(tone.clj:4)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at sound.core$eval3$loading__5569__auto____4.invoke(core.clj:4)
        at sound.core$eval3.invokeStatic(core.clj:4)
        at sound.core$eval3.invoke(core.clj:4)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.Util.loadWithClass(Util.java:250)
        at sound.core.<clinit>(Unknown Source)
Apr 23, 2016 2:36:12 PM clojure.lang.Reflector invokeMatchingMethod
WARNING: 
Apr 23, 2016 2:36:13 PM clojure.lang.Reflector invokeMatchingMethod
SEVERE: Unable to load native libs c and scsynth. Please try an external server with (use 'overtone.core)
--> Loading Overtone...
--> Please boot a server to start making noise:
    * (boot-server)             ; boot default server (honours config)
    * (boot-internal-server)    ; boot an internal server
    * (boot-external-server)    ; boot an external server
    * (connect-external-server) ; connect to an existing external server

--> Booting internal SuperCollider server...
Exception in thread "Thread-16" java.lang.NullPointerException
        at clj_native.structs$byref.invokeStatic(structs.clj:162)
        at clj_native.structs$byref.invoke(structs.clj:158)
        at overtone.sc.machinery.server.native$scsynth.invokeStatic(native.clj:224)
        at overtone.sc.machinery.server.native$scsynth.invoke(native.clj:217)
        at overtone.sc.machinery.server.connection$internal_booter.invokeStatic(connection.clj:185)
        at overtone.sc.machinery.server.connection$internal_booter.invoke(connection.clj:180)
        at overtone.sc.machinery.server.connection$boot_internal_server$fn__10723.invoke(connection.clj:206)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:744)
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.Exception: The following deps took too long (20 seconds) to be satisfied: :server-ready, compiling:(sound/tone.clj:132:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at sound.core$eval3$loading__5569__auto____4.invoke(core.clj:4)
        at sound.core$eval3.invokeStatic(core.clj:4)
        at sound.core$eval3.invoke(core.clj:4)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.Util.loadWithClass(Util.java:250)
        at sound.core.<clinit>(Unknown Source)
Caused by: java.lang.Exception: The following deps took too long (20 seconds) to be satisfied: :server-ready
        at overtone.libs.deps$wait_until_deps_satisfied.invokeStatic(deps.clj:184)
        at overtone.libs.deps$wait_until_deps_satisfied.invoke(deps.clj:168)
        at overtone.libs.deps$wait_until_deps_satisfied.invokeStatic(deps.clj:174)
        at overtone.libs.deps$wait_until_deps_satisfied.invoke(deps.clj:168)
        at overtone.sc.machinery.server.connection$boot$fn__10752.invoke(connection.clj:355)
        at overtone.sc.machinery.server.connection$boot.invokeStatic(connection.clj:340)
        at overtone.sc.machinery.server.connection$boot.invoke(connection.clj:327)
        at overtone.sc.machinery.server.connection$boot.invokeStatic(connection.clj:338)
        at overtone.sc.machinery.server.connection$boot.invoke(connection.clj:327)
        at overtone.sc.machinery.server.connection$boot.invokeStatic(connection.clj:337)
        at overtone.sc.machinery.server.connection$boot.invoke(connection.clj:327)
        at overtone.sc.server$boot_internal_server.invokeStatic(server.clj:142)
        at overtone.sc.server$boot_internal_server.invoke(server.clj:138)
        at sound.tone$eval18624.invokeStatic(tone.clj:132)
        at sound.tone$eval18624.invoke(tone.clj:132)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 39 more
```

**Comment by BorisKourt** [comment]
Ignore that error. I just needed external SuperCollider. Everything appears to work now. 

Thanks for making this script! Super helpful :) 

***
Side Note: that the Cask version (osx homebrew) won't work out of the box as overtone doesn't look for it there. Using the official installer does work. 

You will need to symlink or somehow pass the path to overtone if you want to use the brew one.

**Comment by rogerallen** [comment]
FWIW, here's the spot where supercollider paths are hardcoded:
https://github.com/overtone/overtone/blob/8bb81f9cbb8c99aacea3640a80a827a50ac7bf66/src/overtone/sc/defaults.clj#L55

**Comment by BorisKourt** [comment]
For anyone that might have a future issue with this:

If you are getting `Unable to load library 'scsynth'` and SuperCollider appears to be at the correct location (list linked above) 

Try opening SuperCollider itself, and starting the server. If it fails then that is the cause of that error in your Overtone process.

I don't know if it will always be due to the same thing, but for me it was because something set something (very descriptive) to 44khz and SC wanted 48khz  (or the other way around.)

Hope it saves a bit of time!
